// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using webapi.Models;

namespace webapi.Migrations
{
    [DbContext(typeof(ClientViewContext))]
    [Migration("20171128022724_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("webapi.Models.ClientView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data");

                    b.Property<string>("RemoteAddress");

                    b.Property<string>("RemotePort");

                    b.Property<DateTime>("Time");

                    b.Property<string>("UserAgent");

                    b.HasKey("Id");

                    b.ToTable("ClientViews");
                });
#pragma warning restore 612, 618
        }
    }
}
